### ISSUE TITLE
InstantReset prevent command blocks to select players by team

### ISSUE THREAD

**Issue by idkw** [cybertiger/Bukkit-InstantReset#3]
Hello

I've installed the plugin and it works as expected with spigot 1.8 and last multiverse build.
However when the plugin is loaded I can't select a player who is in a team.

For example run these command in command blocks in the world which is to be reset in the config :
/scoreboard teams add test
/scoreboard teams join @p test
/say @a[team=test]

The first two commands works, but the third doesn't say my name
And as soon as I stopped my server, remove InstantReset and restart the server, the last command and any other comand involving the "team" selector work again.
So there is clearly a conflict between InstantReset and scoreboards.

Can you make a fix for this please ? This prevent me from using this plugin. I intended to use it to reset custom maps with lots of commands blocks.

I know this is a very strange issue. I don't understand why scoreboards are messed up, but please test yourself with spigot 1.8 and only multiverse-core and InstantReset, you will reproduce the issue.

**Comment by cybertiger** [comment]
Thanks for reporting this.

Turns out the scoreboard wasn't being initialized correctly for InstantReset worlds.

Should be fixed in the latest dev build.

**Comment by idkw** [comment]
I tried version 1.5 and sadly the same issue I described remains :/
Commands with team selector doesn't work
