### ISSUE TITLE
Bukkit cowardly refused to unload the world: world

### ISSUE THREAD

**Issue by rohanmcdermott** [cybertiger/Bukkit-InstantReset#5]
Hi this is the plugin I need! I tried it but Im getting this error message:
Bukkit cowardly refused to unload the world: world

Console error:
01.04 16:35:35 [Server] INFO Skipping active world save dir: /plugins/InstantReset/worlds/world.2482467518033154950.world
01.04 16:35:35 [Server] WARN Failed to fully delete unused world save: /plugins/InstantReset/worlds/world

I really need help asap! Thanks

**Comment by cybertiger** [comment]
You can't reset the main world, see the reply on the dev.bukkit.org post, or read the description.
