### ISSUE TITLE
API ERROR

### ISSUE THREAD

**Issue by galaipa** [cybertiger/Bukkit-InstantReset#7]
Hi, I am having this error in the console while using your api.
Error: http://pastebin.com/rxLSVEQd

My code:
Code (Text):
        InstantReset irPlugin = (InstantReset) getServer().getPluginManager().getPlugin("InstantReset");
        if (irPlugin!= null && irPlugin.isEnabled()) {
            InstantResetWorld world = irPlugin.getInstantResetWorld("SkyWars");
            if (world != null) {
                irPlugin.resetWorld(world);
            }

**Comment by cybertiger** [comment]
Should be fixed in 1.10
