### ISSUE TITLE
Support regeneration (new seed) of worlds

### ISSUE THREAD

**Issue by rlf** [cybertiger/Bukkit-InstantReset#9]
The Instant-Reset is a really life-saver.

But. I'd like to use it to also regenerate some worlds.

Could you add support for accepting null as template? And simply generate a new world in that case?
Or something similar.

That way, I can use ir for both resetting worlds (to a previous state), and for getting completely new ones (i.e. so players don't "know their way around" in the newly reset world).

**Comment by cybertiger** [comment]
Generally no, it would not be very instant and would cause significant lag on the server, something which this plugin goes to great lengths to try to avoid.

To reset a world with a new seed without causing lag for other players you'd have to pregenerate the new world before the reset point, and this would be a significant amount of work.
